#!/usr/bin/env python3
"""
Mimir — Code Generation

Generate code with context from capsules.

Usage:
    from intelligence.mimir.generate import MimirGenerate

    generator = MimirGenerate("capsules/")
    code = generator.generate("Write a function to parse JSON")
"""

import json
import os
from pathlib import Path
from typing import List, Dict, Any, Optional
from .search import MimirSearch
from .watermark_llm import MimirLLM


class MimirGenerate:
    """
    Mimir code generator — generates code with context from capsules.
    """

    def __init__(self, capsule_dir: str = "capsules", model: str = "phi3:mini"):
        """
        Initialise generator.

        Args:
            capsule_dir: Directory containing capsules
            model: LLM model to use
        """
        self.search = MimirSearch(capsule_dir)
        self.model = model
        self.llm = None

    def generate(
        self,
        prompt: str,
        context_queries: Optional[List[str]] = None,  # ✅ Optional[List[str]]
        max_tokens: int = 500,
        temperature: float = 0.7,
    ) -> Dict[str, Any]:
        """
        Generate code with context.

        Args:
            prompt: Code generation prompt
            context_queries: Queries to find context
            max_tokens: Max response tokens
            temperature: Sampling temperature

        Returns:
            Dict with code and provenance
        """
        # Find relevant capsules
        results = self.search.search(prompt, limit=3)

        # Build context
        context = self._build_context(results)

        # Try LLM generation
        try:
            self.llm = MimirLLM(model=self.model)
            response = self.llm.generate(
                prompt=f"Generate code for: {prompt}\n\nContext:\n{context}",
                max_tokens=max_tokens,
                temperature=temperature,
            )

            return {
                "code": response["text"],
                "sources": [
                    {
                        "scp_id": r.get("scp_id", "unknown"),
                        "trust": r.get("_trust", 1.0),
                    }
                    for r in results
                ],
                "provenance": response["provenance"],
            }

        except ImportError:
            # Fallback: generate without LLM
            return {
                "code": self._fallback_generate(prompt, results),
                "sources": [
                    {
                        "scp_id": r.get("scp_id", "unknown"),
                        "trust": r.get("_trust", 1.0),
                    }
                    for r in results
                ],
                "provenance": {
                    "generator": "mimir-fallback",
                    "sources": [r.get("scp_id", "unknown") for r in results],
                },
            }

    def _build_context(self, results: List[Dict[str, Any]]) -> str:
        """Build context string from search results."""
        if not results:
            return "No relevant context found."

        context_lines = []
        for r in results:
            scp_id = r.get("scp_id", "unknown")
            intent = r.get("intent", "")
            content = r.get("content", {})

            context_lines.append(f"--- {scp_id} ---")
            context_lines.append(f"Intent: {intent}")

            if isinstance(content, dict):
                for key, value in content.items():
                    if key != "docstring" and key != "summary":
                        continue
                    if value:
                        context_lines.append(f"{key}: {str(value)[:200]}")

        return "\n".join(context_lines)

    def _fallback_generate(self, prompt: str, results: List[Dict]) -> str:
        """Generate code without LLM."""
        if not results:
            return f"# Could not find context for: {prompt}"

        # Use first result as template
        top = results[0]
        scp_id = top.get("scp_id", "unknown")
        intent = top.get("intent", "")

        return f"""
# Generated by Mimir (fallback)
# Based on: {scp_id}
# Context: {intent}
# Original prompt: {prompt}

# TODO: Implement your code here
# Consider using the pattern from {scp_id}
"""


def generate_code(prompt: str, capsule_dir: str = "capsules", model: str = "phi3:mini") -> Dict[str, Any]:
    """Convenience function for code generation."""
    generator = MimirGenerate(capsule_dir, model)
    return generator.generate(prompt)


# ============================================================
# CLI
# ============================================================

def main():
    """Test generation."""
    import argparse
    import sys

    parser = argparse.ArgumentParser(description="Mimir — Code Generation")
    parser.add_argument("prompt", type=str, help="Code generation prompt")
    parser.add_argument("--capsules", "-c", type=str, default="capsules", help="Capsule directory")
    parser.add_argument("--model", "-m", type=str, default="phi3:mini", help="LLM model")

    args = parser.parse_args()

    print(f"🔨 Mimir — Code Generation")
    print(f"   Prompt: {args.prompt}")
    print("=" * 60)

    result = generate_code(args.prompt, args.capsules, args.model)

    print("\n📝 Generated Code:")
    print("=" * 60)
    print(result["code"])

    print("\n📊 Sources:")
    for source in result.get("sources", []):
        print(f"   - {source.get('scp_id', 'unknown')} (λ: {source.get('trust', 1.0):.2f})")


if __name__ == "__main__":
    main()